apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster-role-binding.yaml
  - keycloak/provider-config.yaml
  - keycloak/provider-credentials.yaml
  - keycloak/patch.yaml
