apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - github.com/tim-stasse/gitops-catalog/openshift-gitops-operator/instance/overlays/default?ref=main

components:
  - github.com/tim-stasse/gitops-catalog/openshift-gitops-operator/instance/components/application-controller-cluster-admin?ref=main
  - github.com/tim-stasse/gitops-catalog/openshift-gitops-operator/instance/components/kustomize-build-enable-helm?ref=main

patches:
  - target:
      kind: Group
      name: gitops-admins
    patch: |-
      - op: replace
        path: /users
        value:
          - kubeadmin
