apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - console-link.yaml
  - password-generator.yaml
  - initial-user-passwords.yaml
  - keycloak-realm.yaml
  - clients.yaml
  - groups.yaml
  - users.yaml
